namespace: open-cluster-management

resources:
- clusterrole.yaml
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml

images:
- name: multicluster-mesh-addon
  newName: quay.io/morvencao/multicluster-mesh-addon
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
