kind: Deployment
apiVersion: apps/v1
metadata:
  name: mesh-addon
  labels:
    app: mesh-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mesh-addon
  template:
    metadata:
      labels:
        app: mesh-addon
    spec:
      serviceAccountName: mesh-addon-sa
      containers:
      - name: mesh-addon
        image: mesh-addon-image
        imagePullPolicy: IfNotPresent
        env:
        - name: MESH_ADDON_IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              name: image-config
              key: MESH_ADDON_IMAGE_NAME
        args:
          - "controller"

