kind: Deployment
apiVersion: apps/v1
metadata:
  name: multicluster-mesh-agent
  namespace: {{ .AddonInstallNamespace }}
  labels:
    app: multicluster-mesh-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-mesh-agent
  template:
    metadata:
      labels:
        app: multicluster-mesh-agent
    spec:
      serviceAccountName: multicluster-mesh-agent
      volumes:
      - name: hub-kubeconfig
        secret:
          secretName: {{ .KubeConfigSecret }}
      containers:
      - name: multicluster-mesh-agent
        image: {{ .Image }}
        imagePullPolicy: IfNotPresent
        command:
        - "/multicluster-mesh-addon"
        - "agent"
        - "--hub-kubeconfig=/var/run/hub/kubeconfig"
        - "--cluster-name={{ .ClusterName }}"
        - "--addon-namespace={{ .AddonInstallNamespace }}"
        volumeMounts:
        - name: hub-kubeconfig
          mountPath: /var/run/hub
